using System;
using System.Text;
using Newtonsoft.Json;

namespace Authware.Models;

/// <summary>
///     Represents a response from an executed API
/// </summary>
public class ApiResponse
{
    /// <summary>
    ///     The message from the Authware API
    /// </summary>
    [JsonProperty("message")]
    public string Message { get; set; }

    /// <summary>
    ///     The request ID generated by the designated proxy server, this can be used to fetch the specific request details
    ///     back from the user
    /// </summary>
    [JsonProperty("request_id")]
    public Guid RequestId { get; set; }

    /// <summary>
    ///     The Base64 encoded response from your API
    /// </summary>
    [JsonProperty("response")]
    public string EncodedResponse { get; set; }

    /// <summary>
    ///     If the request was successful
    /// </summary>
    [JsonProperty("is_success")]
    public bool Success { get; set; }

    /// <summary>
    ///     The plaintext response which has been decoded from Base64, this will be null if the response could not be decoded
    /// </summary>
    public string DecodedResponse
    {
        get
        {
            try
            {
                return Encoding.UTF8.GetString(Convert.FromBase64String(EncodedResponse));
            }
            catch (Exception)
            {
                // ignored, if not caught and the API is configured to not respond, this will throw an exception.
                return null;
            }
        }
    }

    public override string ToString()
    {
        return DecodedResponse;
    }

    /// <summary>
    ///     Whether the response is going to be a actual response served by the API or a status code, due to the configuration
    ///     of your API.
    /// </summary>
    public bool CanReturnResponse
    {
        get
        {
            try
            {
                return !int.TryParse(Encoding.UTF8.GetString(Convert.FromBase64String(EncodedResponse)), out _);
            }
            catch (Exception)
            {
                return false;
            }
        }
    }
}