using System;
using System.Text;
using Newtonsoft.Json;

namespace Authware.Models
{
    /// <summary>
    ///     Represents a response from an executed API
    /// </summary>
    public class ApiResponse
    {
        /// <summary>
        ///     The message from the Authware API
        /// </summary>
        [JsonProperty("message")]
        public string Message { get; set; }

        /// <summary>
        ///     The request ID generated by the designated proxy server, this can be used to fetch the specific request details
        ///     back from the user
        /// </summary>
        [JsonProperty("request_id")]
        public Guid RequestId { get; set; }

        /// <summary>
        ///     The Base64 encoded response from your API
        /// </summary>
        [JsonProperty("response")]
        public string EncodedResponse { get; set; }

        /// <summary>
        ///     If the request was successful
        /// </summary>
        [JsonProperty("is_success")]
        public bool Success { get; set; }

        /// <summary>
        ///     The plaintext response which has been decoded from Base64
        /// </summary>
        public string DecodedResponse => Encoding.UTF8.GetString(Convert.FromBase64String(EncodedResponse));

        public override string ToString()
        {
            return DecodedResponse;
        }
    }
}